<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

// do_action( 'genesis_before_footer' );
// do_action( 'genesis_footer' );
// do_action( 'genesis_after_footer' );

?>

<div id="google-maps-footer" class="google-maps-footer"></div>

<footer class="footer">
	<div class="container">

		<div class="column-footer">
			<?php
				wp_nav_menu(
					array(
						'menu' 				=> 'footer-menu',
						'menu_class' 		=> 'footer-menu',
						'menu_id' 			=> 'menu-footer-menu',
						'container' 		=> 'nav',
						'container_class' 	=> 'nav',
						'container_id' 		=> 'footer-menu',
						'echo' 				=> true,
						'depth' 			=> 1,
						'theme_location' 	=> 'footer-menu',
					)
				);
			?>			
			<div class="footer-logo">
				<a href="<?php echo get_home_url(); ?>"><img class="main-logo" src="<?php echo get_stylesheet_directory_uri(); ?>/images/baton-rouge-dental-white.png" /></a>
			</div>			
		</div>

		<div class="column-footer">
			<?php dynamic_sidebar( 'footer-1' ); ?>
		</div>

		<div class="column-footer">
			<?php dynamic_sidebar( 'footer-2' ); ?>
		</div>

		<div class="clearfix"></div>	
	</div>
</footer>

<div class="footer-copyright">
	<div class="container">
		<p class="content">Copyright © 2014-<?php echo date('Y'); ?> | Birmingham Dental Assistant School is a division of Vandelay Education LLC and Licensed and regulated by the Alabama Department of Postsecondary Education, plus Alabama Commission on Higher Education.</p>
	</div>
</div>

<?php


genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-container',
) );

do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup( array(
	'close'   => '</body>',
	'context' => 'body',
) );

?>
</html>
