<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>
</head>



<?php
genesis_markup( array(
	'open'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-container',
) );
?>

<header>
	

	<div class="top-header">
		<div class="container">
			<ul class="social-links">
				<li><a target="_blank" href="https://www.instagram.com/birminghamdas"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
				<li><a target="_blank" href="https://www.facebook.com/birminghamdentalassistant"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
				<li><a href="tel:205-530-6694" class="phone"><i class="fa fa-phone" aria-hidden="true"></i>205-530-6694</a></li>
			</ul>			
		</div>
	</div>

	<div class="seconday-header">
		<div class="container">
			<div class="logo">
				<a href="<?php echo get_home_url(); ?>"><img class="main-logo" src="<?php echo get_stylesheet_directory_uri(); ?>/images/baton-rouge-dental.png" /></a>
			</div>
			<div class="main-menu brm-main-menu">
				<?php
					wp_nav_menu(
						array(
							'menu' 				=> 'primary-menu',
							'menu_class' 		=> 'menu genesis-nav-menu js-superfish sf-js-enabled sf-arrows',
							'menu_id' 			=> 'menu-primary-menu',
							'container' 		=> 'nav',
							'container_class' 	=> 'nav-header',
							'container_id' 		=> 'primary-menu',
							'echo' 				=> true,
							'depth' 			=> 1,
							'theme_location' 	=> 'primary',
						)
					);
				?>
			</div>
		</div>		
	</div>

	<?php if(!is_front_page()): ?>
		<div class="container"><?php echo genesis_breadcrumb(); ?></div>
	<?php endif; ?>
</header>

<?php
// do_action( 'genesis_before_header' );
// do_action( 'genesis_header' );
// do_action( 'genesis_after_header' );

// 

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );